"""add soft delete to financial records

Revision ID: 9c23ca798fa6
Revises: f08b44c54d74
Create Date: 2026-09-01 14:44:04.701623

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c23ca798fa6'
down_revision: Union[str, Sequence[str], None] = 'f08b44c54d74'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    op.add_column(
        "donations",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

    op.add_column(
        "expenses",
        sa.Column(
            "is_active",
            sa.Boolean(),
            nullable=False,
            server_default=sa.true(),
        ),
    )

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'is_active')
    op.drop_column('donations', 'is_active')
    # ### end Alembic commands ###
